#!/usr/bin/env python3
"""
Material Passport — hash 验证脚本
验证 structured_contract.json 的 _passport.contract_hash 完整性。

用法:
  python scripts/passport_verify.py <path/to/structured_contract.json>

退出码:
  0 = PASS (hash 匹配)
  1 = NO_PASSPORT (无 _passport 字段，旧格式)
  2 = TAMPERED (hash 不匹配，可能被篡改)
  3 = INVALID_JSON (文件无法解析)
"""

import json
import hashlib
import sys
import os
from datetime import datetime, timezone


def compute_hash(data: dict, algorithm: str = "sha256") -> str:
    """计算排除 _passport 字段后的契约 hash"""
    data_without_passport = {k: v for k, v in data.items() if k != "_passport"}
    canonical_json = json.dumps(data_without_passport, sort_keys=True, separators=(",", ":"))
    h = hashlib.new(algorithm)
    h.update(canonical_json.encode("utf-8"))
    return f"{algorithm}:{h.hexdigest()}"


def verify_passport(contract_path: str) -> dict:
    """验证 Material Passport，返回结果字典"""
    result = {
        "file": contract_path,
        "status": "UNKNOWN",
        "checked_at": datetime.now(timezone.utc).isoformat(),
        "details": {}
    }

    if not os.path.exists(contract_path):
        result["status"] = "FILE_NOT_FOUND"
        result["details"]["error"] = f"File not found: {contract_path}"
        return result

    try:
        with open(contract_path, "r", encoding="utf-8") as f:
            contract = json.load(f)
    except json.JSONDecodeError as e:
        result["status"] = "INVALID_JSON"
        result["details"]["error"] = str(e)
        return result

    passport = contract.get("_passport")
    if not passport:
        result["status"] = "NO_PASSPORT"
        result["details"]["warning"] = (
            "No _passport field found. This contract was generated by an older version "
            "of TestVDB (pre-v2.0). Hash verification skipped."
        )
        return result

    expected_hash = passport.get("contract_hash")
    algorithm = passport.get("contract_hash_algorithm", "sha256")

    if not expected_hash:
        result["status"] = "NO_HASH"
        result["details"]["error"] = "_passport exists but contract_hash is missing"
        return result

    try:
        actual_hash = compute_hash(contract, algorithm)
    except ValueError:
        result["status"] = "UNSUPPORTED_ALGORITHM"
        result["details"]["error"] = f"Unsupported hash algorithm: {algorithm}"
        return result

    result["details"]["expected_hash"] = expected_hash
    result["details"]["actual_hash"] = actual_hash
    result["details"]["algorithm"] = algorithm
    result["details"]["schema_version"] = passport.get("schema_version", "unknown")
    result["details"]["generated_at"] = passport.get("generation", {}).get("generated_at", "unknown")

    if actual_hash == expected_hash:
        result["status"] = "PASS"
    else:
        result["status"] = "TAMPERED"
        result["details"]["error"] = (
            f"Hash mismatch! Contract content has been modified since generation. "
            f"Expected: {expected_hash[:32]}..., Actual: {actual_hash[:32]}..."
        )

    return result


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/passport_verify.py <path/to/structured_contract.json>")
        sys.exit(3)

    contract_path = sys.argv[1]
    result = verify_passport(contract_path)
    print(json.dumps(result, indent=2, ensure_ascii=False))

    status_map = {"PASS": 0, "NO_PASSPORT": 1, "TAMPERED": 2,
                  "INVALID_JSON": 3, "FILE_NOT_FOUND": 3, "NO_HASH": 2}
    sys.exit(status_map.get(result["status"], 3))


if __name__ == "__main__":
    main()
